#Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.
n=int(input('Digite um número para mostrar sua tabuada :'))
print('-'*12)
print('{} x {}={}'.format(n,1,n*1))
print('{} x {}={}'.format(n,1,n*2))
print('{} x {}={}'.format(n,1,n*3))
print('{} x {}={}'.format(n,1,n*4))
print('{} x {}={}'.format(n,1,n*5))
print('{} x {}={}'.format(n,1,n*6))
print('{} x {}={}'.format(n,1,n*7))
print('{} x {}={}'.format(n,1,n*8))
print('{} x {}={}'.format(n,1,n*9))
print('-'*12)